name: C/C++ CI RUN TESTS
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Set up MinGW
    - uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64
    - uses: actions/checkout@v2
    - name: run tests
      run: make test-run
