name: C/C++ CI RUN TESTS
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install MinGW
      uses: egor-tensin/setup-mingw@v2
      if: ${{ matrix.platform }} == windows-latest
    - uses: actions/checkout@v2
    - name: run tests
      run: make test-run
